version: '3.8'

services:
  frontend:
    image: vue-frontend:latest
    build: ./frontend
    container_name: vue-frontend
    working_dir: /frontend
    volumes:
      - /frontend/node_modules/
      - ./frontend:/frontend
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development

  backend:
    image: go-backend:latest
    build: ./backend
    container_name: go-backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - 8080:8080
    environment:
      - DB_TYPE=firestore
      - RUN_ENV=mock
      - MONGO_URI=mongodb://gdsf:gdsf@db:27017
      - FIRESTORE_URI=fsemudb://gdsf:gdsf@firestore_emulator:28017
      - USUGDSF_AUTH_TOKEN=fakeHwVJzEu2wTRBK4wNu80C
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:8080
      - FIRESTORE_PROJECT_ID=dummy-project-id
    command: gin --appPort 8080 -i run .

  firestore_emulator:
    image: mtlynch/firestore-emulator
    container_name: 'firestore_emu'
    environment:
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - PORT=28017
    ports:
      - 28017:28017

  db:
    image: 'mongo'
    container_name: 'gdsf-db'
    environment:
      - MONGO_INITDB_DATABASE=gdsf
      - MONGO_INITDB_ROOT_USERNAME=gdsf
      - MONGO_INITDB_ROOT_PASSWORD=gdsf
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'

  gcs:
    image: fsouza/fake-gcs-server
    container_name: cloud-storage
    build: ./gcs
    volumes:
      - gcs-volume:/data
    ports:
      - 4443:4443
    command: "-scheme http"

volumes:
  mongo-volume:
  gcs-volume:
